### ISSUE TITLE
About the dam break problem

### ISSUE THREAD

**Issue by FiniteTsai** [adevaucorbeil/karamelo#1]
Dear karamelo friend,

I like the karamelo very much. Many thanks for its innovation. I just wonder where can I find the dam break problem, in sec 4.5 of CPM paper.

best regard
Finite

**Comment by adevaucorbeil** [comment]
Thank you so much for your interest. You can now find the input file for the dam break problem in the examples/Dam-break/ subdirectory. The repository has been updated accordingly.
Cheers
Alban
