### ISSUE TITLE
Error in Installing and running karamelo

### ISSUE THREAD

**Issue by saurabhsinghiitd** [adevaucorbeil/karamelo#13]
I am using windows 11 and I am trying to install Karamelo using the instructions in 'Install.txt'

In beginning, I was facing error while executing command -
"cmake -DCMAKE_BUILD_TYPE=release build"
CMake Error: The source directory "Path2Directory/karamelo/build" does not exist.

As per suggestions on the internet, I made a directory with the name 'build' and included the file 'CMakeLists.txt' in the build directory and then executed the 'cmake' command  -  "cmake -DCMAKE_BUILD_TYPE=release build"
This is the response I am getting

 PS E:\Path2Directory\karamelo> cmake -DCMAKE_BUILD_TYPE=release build
-- Building for: Visual Studio 14 2015
-- Found Git: C:/Program Files/Git/cmd/git.exe (found version "2.40.1.windows.1") 
Git found: C:/Program Files/Git/cmd/git.exe
CMake Deprecation Warning at CMakeLists.txt:10 (cmake_policy):
  The OLD behavior for policy CMP0004 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.

-- Selecting Windows SDK version 10.0.14393.0 to target Windows 10.0.22621.
-- The C compiler identification is MSVC 19.0.24210.0
-- The CXX compiler identification is MSVC 19.0.24210.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Could NOT find MPI_C (missing: MPI_C_WORKS) 
-- Could NOT find MPI_CXX (missing: MPI_CXX_WORKS) 
CMake Error at C:/Program Files/CMake/share/cmake-3.26/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find MPI (missing: MPI_C_FOUND MPI_CXX_FOUND)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.26/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.26/Modules/FindMPI.cmake:1837 (find_package_handle_standard_args)
  CMakeLists.txt:20 (find_package)

-- Configuring incomplete, errors occurred!

It appears that the msmpisetup.exe and msmpisdk.msi files are supported by only windows 10 as mentioned in documentation.
And since I am using windows 11, Could that be an issue, or is it something else?
Kindly help.

**Comment by adevaucorbeil** [comment]
You did right to create a build directory. However, you do not have to copy the CMakeLists.txt file into it. Simply by running 'cmake -DCMAKE_BUILD_TYPE=release build ../' directly from the build directory would work.
It seems like cmake cannot find MPI. This is therefore a problem with cmake, not Karamelo.
I am afraid I am not competent to help you here as I do not have experience with Window. If it was on Linux I could have been of some help...
