### ISSUE TITLE
about cutting

### ISSUE THREAD

**Issue by fengsim** [adevaucorbeil/karamelo#14]
when i run the example for cutting, the temperature has some problems, i get the following output, 

Creating new Temperature with ID: tpw
Error at line 81: Error: not enough arguments.
Usage: temperature(temp-ID, plastic_work, chi, cp, kappa, alpha, T0, Tm)
 raised at (/home/jiping/Downloads/karamelo-master/src/temperature_plastic_work.cpp,34)
Last command: temperature(tpw, plastic_work, chi, rho, cp)

would you please tell me how to fix it? Thanks a lot.

**Comment by adevaucorbeil** [comment]
The error message is pretty clear.
You passed this command: temperature(tpw, plastic_work, chi, rho, cp)
when it is expecting something like: temperature(temp-ID, plastic_work, chi, cp, kappa, alpha, T0, Tm)

This is not a bug. This is an input file error.
