### ISSUE TITLE
Error while running `two_disks` example

### ISSUE THREAD

**Issue by lokitkhemka** [adevaucorbeil/karamelo#17]
I am getting an error while running karamelo for `two_disks.mpm` example. The log is as follows:

```
Solid sBall2 total volume = 0.13
Solid sBall2 total mass = 130
208 particles from solid sBall1 found
208 particles from solid sBall2 found
v = 0.1
Creating new fix with ID: v0Ball1
Creating new fix with ID: v0Ball2
N_log = 10
dumping_interval = 10
Creating new dump with ID: dump1
Creating new dump with ID: dump2
Error at line 39: Unknown dump style pyplot.
 raised at (/home/loki/workspace/karamelo/src/output.cpp,231)
Last command: dump(dump3, all, pyplot, 1, dump.*.pdf, 500, 500)

```

I have tried installing `matplotlib` for `Python2.7` and `matplotlib` for `python 3.10` that is installed on my system. I also made sure to add the following lines in `~/.bashrc` file:

```
CPATH=$CPATH:/usr/include/eigen3:~/workspace/karamelo/third-party/gzstream:~/workspace/karamelo/deps/matplotlib-cpp:/usr/include/python2.7
export CPATH

LIBRARY_PATH=$LIBRARY_PATH:/usr/include/eigen3:~/workspace/karamelo/third-party/gzstream:~/workspace/karamelo/deps/matplotlib-cpp:/usr/include/python2.7
export LIBRARY_PATH

```

**Comment by adevaucorbeil** [comment]
Thank you so much for reporting this bug and helping Karamelo get better.
This bug is now fixed.
In return, would you be so kind to help me out by filling out our survey: [https://forms.gle/aHZ9s5Pc4aTQLZ2b8](https://forms.gle/aHZ9s5Pc4aTQLZ2b8).
Thank you
