### ISSUE TITLE
Files missing in the code and errors occurred in the compiling process

### ISSUE THREAD

**Issue by fengzekang** [adevaucorbeil/karamelo#2]
Hello, @adevaucorbeil 
I noticed that the file "fix_contact_min_penetration.h" is missing. and this cause the compiling failed.
Could you please check it? 
Thanks a lot.

**Comment by adevaucorbeil** [comment]
Hello @fengzekang,
Thanks for submitting this issue. There was indeed some file missing and a little series of small bugs preventing a complete compilation of the code.
The last commit e0e5d40 solves these issues.
Cheers
