### ISSUE TITLE
On the Bouncing balls example

### ISSUE THREAD

**Issue by vryy** [adevaucorbeil/karamelo#3]
Hello

When running the Bouncing_balls example, I encounter this error:

Running on 1 procs
In Input::file()
E = 1e+06
nu = 0.3
K = 833333
mu = 384615
rho = 1050
lambda = 576923
c = 30.8607
L = 1
hL = 0.5
A_zy = 1
FLIP = 0.99
In ULMPM::ULMPM()
Setting up linear basis functions
Setting up linear basis functions
N = 10
cellsize = 0.1
Set dimension to 2
In Universe::set_proc_grid()
In Grid::init() with proc 0
proc 0 nx=21	ny=21	nz=1
proc 0 noffsetlo=[0,0,0]
proc 0 noffsethi_=[20,20,0]
delta=0.1
R = 0.4
Creating new region with ID: rBall1
Initiate Cylinder
In region::options()
axis, c1, c2, R = z	-0.5	-0.5	0.4
Creating new region with ID: rBall2
Initiate Cylinder
In region::options()
axis, c1, c2, R = z	0.5	0.5	0.4
Creating new mat with ID: mat1
Creating new solid with ID: sBall1
Error at line 35: Error, keyword rBall1 unknown!
Usage: solid(solid-ID, file, filename, material-ID, h, T0)
Usage: solid(solid-ID, mesh, meshfile, material-ID, h, T0)
Usage: solid(solid-ID, region, region-ID, N_ppc1D, material-ID, cell-size, T0)
 raised at (/home/hbui/sw2/karamelo/src/solid.cpp,114)
Last command: solid(sBall1, rBall1, 2, mat1, cellsize)

Can you help to look at it, since I'm quite new to Karamelo ?

Thanks
Giang

**Comment by adevaucorbeil** [comment]
Dear Giang,

Commit 398d312f6e482e909b17204ce8026c6918e642e0 solves this issue. Please pull and try again.

Sorry for the disagreement.
Alban

**Comment by vryy** [comment]
Thank you Alban. That solved the problem.
