### ISSUE TITLE
Is there some example code to simulate "moving liquid or smoke"？

### ISSUE THREAD

**Issue by xiaoqiang-wang** [adevaucorbeil/karamelo#6]
😄  Hello, my friend,
Is there some example code to simulate "moving liquid or smoke"？

**Comment by adevaucorbeil** [comment]
Hi,
There are two examples involving moving fluids: dam-break and FSI (Fluid Structure Interaction). There is no example of moving smoke. This is not something on which my collaborators and I work on.

Best regards
